### ISSUE TITLE
Error when enabling customfoodbar button in Config Manager

### ISSUE THREAD

**Issue by simdo01** [thedefside/BetterUI#31]
Error when enabling customfoodbar button in config manager

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BetterUI.Patches.CustomElements+FoodBar.Update (Player player) (at <ba9fa52f025a4f1aab3fa5a0598003a4>:0)
BetterUI.GameClasses.BetterHud.UpdateFood (Player player) (at <ba9fa52f025a4f1aab3fa5a0598003a4>:0)
(wrapper dynamic-method) Hud.DMD<Hud::UpdateFood>(Hud,Player)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)

**Comment by thedefside** [comment]
Thank you for the report. It might take me a couple days to get to it.

**Comment by Goldenrevolver** [comment]
all four custom bar elements really don't like it when you change the config ingame since they only get created in Awake, so they all throw null reference exceptions if you enable or disable them at the wrong time (the food bar throws different ones than the health and stamina bar though). Curiously, the creation of all but the xp bar is also dependent on enablePlayerHudEditing being enabled. Getting all the null references out of the way is not difficult of course, but would loading them at run time be worth the work?
