### ISSUE TITLE
Console Spam ArgumentOutOfRangeException after 2.3.2

### ISSUE THREAD

**Issue by DaveKX** [thedefside/BetterUI#40]
Hello, after updating to 2.3.2 I'm now getting spammed on console with this error (although I didn't really notice any problems while playing?). I can attach my log if needed!

```
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterUI.GameClasses.BetterHotkeyBar.PatchHotkeyBar (HotkeyBar& __instance, Player& player) (at <782a6fbf20064a6bb00c8bb10338286a>:0)
(wrapper dynamic-method) HotkeyBar.DMD<HotkeyBar::UpdateIcons>(HotkeyBar,Player)
HotkeyBar.Update () (at <035307060cbb4b30b916cd82ebd80490>:0)
```

**Comment by thedefside** [comment]
Do you have an equipment/quick slots mod installed?

**Comment by DaveKX** [comment]
Yeah, ComfyQuickSlots

**Comment by thedefside** [comment]
If you remove that mod, does the error go away?

**Comment by DaveKX** [comment]
Yes it did go away, is that extra row in the inventory added by the other mod the problem then?

**Comment by thedefside** [comment]
I'm not sure if it's the inventory, the error is coming from the HotBar patch. The same thing happens with the equipment slots for OdinsQOL. I believe it's just a conflict with both mods changing the same method. I think RandyKnapps Equipment and Quick Slots mod works with Better UI. Better UI even makes it so you can move those windows around.

**Comment by DaveKX** [comment]
Great! I was using this one instead of Randy's due to the lost equipment on death bug, but in the latest update they are saying this bug is now fixed, so I will switch back to it. Thank you and you can close this one then :)

**Comment by thedefside** [comment]
Well, they have said that bug was fixed in EAQS many times...

**Comment by DaveKX** [comment]
I hope the time has finally come... xD

**Comment by Goldenrevolver** [comment]
now it shouldn't error anymore. why they add items into the hotbar items list but don't increase the hotbar elements list is beyond me. also this won't get released immediately unless thedefside is in the mood for it

**Comment by DaveKX** [comment]
Sure, no problem. Thanks you guys for the fast helping

**Comment by thedefside** [comment]
@DaveKX can you try the pre-release version and see if that solves your issue?

https://github.com/thedefside/BetterUI/releases/tag/v2.3.3-pre-release

**Comment by DaveKX** [comment]
Hey, just tested it now and no more errors with the ComfyQuickSlots mod at the console with this pre-release version! Some of the config in-game UI are a bit messy tho, but I guess it is because it's still the pre-release

**Comment by thedefside** [comment]
Could you expand on the 'messy' part?

**Comment by DaveKX** [comment]
Some of the configs that are now buttons have their text wrong, I think? Like the one that is 'Items slash max room' or the custom bars with 'OnX degrees', and I noticed that the custom bars 'degree' configs are being reseted to default when I overwrite the 2.3.2 dll with the 2.3.3, maybe it's because I'm not 'updating' it through r2modman? Idk

[2.3.2](https://imgur.com/a/2g3H3yX)
[2.3.3](https://imgur.com/a/aaXLmoc)

**Comment by BruceOfTheBow** [comment]
Submitted a fix for this with PR #41

**Comment by Goldenrevolver** [comment]
@BruceOfTheBow great way to get around the issue. good job

@DaveKX those are intentional changes. having these set options (enum values) makes the config options easier to understand than multiple bools and floats that depend on one another. the "slash" is simply because we can't use special characters in an enum. so the display option "x slash y" simply means it displays it as "x / y". for the "OnX Degrees" it's similar. I can't start an enum with a number (for technical reasons), so I started it with the state, "on" rather than "off" (which is the first option). then the enum to text parser of the ingame config manager messes up and forgets to put a space between a letter and a number, so that's not really something we can change. we write enums as one word, e.g. "DoStuffLikeThis". we have to rely on the way the config manager displays it whether it looks good (for programmers no spaces looks good already of course :D )

we can rename them to other things like OnRotatedTo90Deg or something, if you have any better ideas before release let use know. changing these means resetting configs most of the time, so we want to do that before public release

**Comment by DaveKX** [comment]
I know that the set options are intended, didn't know that you couldn't use special characters on it tho. Then the names are good as they are imo, all of them are very self explanatory to me at least. And you said as well that when you changes those configs or their names idk, it resets to default, so all I said is actually intended behavior XD. All good then, thank you.

**Comment by MLNW** [comment]
I just saw this note in the ComfyArmorAndQuickSlots mod:
> If using better UI set showDurabilityColor to disabled to prevent error log spam.

**Comment by BruceOfTheBow** [comment]
@MLNW Yeah I believe 2.3.2 removed the disable for that and it's been reimplemented for later versions. PR #41 will fix the error as soon as it's pulled in to the next release so nothing has to be disabled and showDurabilityColor can be used. I will update the CQS documentation accordingly on its release
